# Generated by Django 4.0.7 on 2023-02-27 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='testform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionTittle', models.CharField(max_length=200)),
                ('questionName', models.CharField(max_length=250)),
                ('questionTestform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formtest.testform')),
            ],
        ),
        migrations.CreateModel(
            name='answerusr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerusrToquestion', models.CharField(max_length=10)),
                ('answerusrDate', models.DateTimeField(auto_now_add=True)),
                ('answerusrMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('answerusrQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formtest.question')),
            ],
        ),
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerDescription', models.CharField(max_length=250)),
                ('answerRight', models.BooleanField(default=True)),
                ('answerQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formtest.question')),
            ],
        ),
    ]
